#!/bin/sh

cd ../case1_1
sbatch main.job
cd ../case1_2
sbatch main.job
cd ../case1_3
sbatch main.job
cd ../case1_4
sbatch main.job
cd ../case1_5
sbatch main.job
cd ../case1_6
sbatch main.job
cd ../case1_7
sbatch main.job
cd ../case1_8
sbatch main.job
cd ../case1_9
sbatch main.job
cd ../case1_10
sbatch main.job
cd ../case1_11
sbatch main.job
cd ../case1_12
sbatch main.job
cd ../case1_13
sbatch main.job
cd ../case1_14
sbatch main.job
cd ../case1_15
sbatch main.job
cd ../case1_16
sbatch main.job
cd ../case1_17
sbatch main.job
cd ../case1_18
sbatch main.job
cd ../case1_19
sbatch main.job
cd ../case1_20
sbatch main.job
cd ../case2_1
sbatch main.job
cd ../case2_2
sbatch main.job
cd ../case2_3
sbatch main.job
cd ../case2_4
sbatch main.job
cd ../case2_5
sbatch main.job
cd ../case2_6
sbatch main.job
cd ../case2_7
sbatch main.job
cd ../case2_8
sbatch main.job
cd ../case2_9
sbatch main.job
cd ../case2_10
sbatch main.job
cd ../case2_11
sbatch main.job
cd ../case2_12
sbatch main.job
cd ../case2_13
sbatch main.job
cd ../case2_14
sbatch main.job
cd ../case2_15
sbatch main.job
cd ../case2_16
sbatch main.job
cd ../case2_17
sbatch main.job
cd ../case2_18
sbatch main.job
cd ../case2_19
sbatch main.job
cd ../case2_20
sbatch main.job
cd ../case3_1
sbatch main.job
cd ../case3_2
sbatch main.job
cd ../case3_3
sbatch main.job
cd ../case3_4
sbatch main.job
cd ../case3_5
sbatch main.job
cd ../case3_6
sbatch main.job
cd ../case3_7
sbatch main.job
cd ../case3_8
sbatch main.job
cd ../case3_9
sbatch main.job
cd ../case3_10
sbatch main.job
cd ../case3_11
sbatch main.job
cd ../case3_12
sbatch main.job
cd ../case3_13
sbatch main.job
cd ../case3_14
sbatch main.job
cd ../case3_15
sbatch main.job
cd ../case3_16
sbatch main.job
cd ../case3_17
sbatch main.job
cd ../case3_18
sbatch main.job
cd ../case3_19
sbatch main.job
cd ../case3_20
sbatch main.job
cd ../case4_1
sbatch main.job
cd ../case4_2
sbatch main.job
cd ../case4_3
sbatch main.job
cd ../case4_4
sbatch main.job
cd ../case4_5
sbatch main.job
cd ../case4_6
sbatch main.job
cd ../case4_7
sbatch main.job
cd ../case4_8
sbatch main.job
cd ../case4_9
sbatch main.job
cd ../case4_10
sbatch main.job
cd ../case4_11
sbatch main.job
cd ../case4_12
sbatch main.job
cd ../case4_13
sbatch main.job
cd ../case4_14
sbatch main.job
cd ../case4_15
sbatch main.job
cd ../case4_16
sbatch main.job
cd ../case4_17
sbatch main.job
cd ../case4_18
sbatch main.job
cd ../case4_19
sbatch main.job
cd ../case4_20
sbatch main.job
cd ../case5_1
sbatch main.job
cd ../case5_2
sbatch main.job
cd ../case5_3
sbatch main.job
cd ../case5_4
sbatch main.job
cd ../case5_5
sbatch main.job
cd ../case5_6
sbatch main.job
cd ../case5_7
sbatch main.job
cd ../case5_8
sbatch main.job
cd ../case5_9
sbatch main.job
cd ../case5_10
sbatch main.job
cd ../case5_11
sbatch main.job
cd ../case5_12
sbatch main.job
cd ../case5_13
sbatch main.job
cd ../case5_14
sbatch main.job
cd ../case5_15
sbatch main.job
cd ../case5_16
sbatch main.job
cd ../case5_17
sbatch main.job
cd ../case5_18
sbatch main.job
cd ../case5_19
sbatch main.job
cd ../case5_20
sbatch main.job
cd ../case6_1
sbatch main.job
cd ../case6_2
sbatch main.job
cd ../case6_3
sbatch main.job
cd ../case6_4
sbatch main.job
cd ../case6_5
sbatch main.job
cd ../case6_6
sbatch main.job
cd ../case6_7
sbatch main.job
cd ../case6_8
sbatch main.job
cd ../case6_9
sbatch main.job
cd ../case6_10
sbatch main.job
cd ../case6_11
sbatch main.job
cd ../case6_12
sbatch main.job
cd ../case6_13
sbatch main.job
cd ../case6_14
sbatch main.job
cd ../case6_15
sbatch main.job
cd ../case6_16
sbatch main.job
cd ../case6_17
sbatch main.job
cd ../case6_18
sbatch main.job
cd ../case6_19
sbatch main.job
cd ../case6_20
sbatch main.job
cd ../case7_1
sbatch main.job
cd ../case7_2
sbatch main.job
cd ../case7_3
sbatch main.job
cd ../case7_4
sbatch main.job
cd ../case7_5
sbatch main.job
cd ../case7_6
sbatch main.job
cd ../case7_7
sbatch main.job
cd ../case7_8
sbatch main.job
cd ../case7_9
sbatch main.job
cd ../case7_10
sbatch main.job
cd ../case7_11
sbatch main.job
cd ../case7_12
sbatch main.job
cd ../case7_13
sbatch main.job
cd ../case7_14
sbatch main.job
cd ../case7_15
sbatch main.job
cd ../case7_16
sbatch main.job
cd ../case7_17
sbatch main.job
cd ../case7_18
sbatch main.job
cd ../case7_19
sbatch main.job
cd ../case7_20
sbatch main.job
